version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: c4gt
      POSTGRES_PASSWORD: c4gt
      POSTGRES_DB: c4gt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgresql://c4gt:c4gt@postgres:5432/c4gt
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
